# fly.toml app configuration file generated for fso-p on 2023-05-10T00:57:59-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[env]
  PORT = "3001"

app = "fso-p"
primary_region = "dfw"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
